# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('direction', models.CharField(choices=[('1', 'Incoming'), ('2', 'Outgoing')], max_length=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.Account')),
                ('related_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_payments', to='accounts.Account')),
            ],
        ),
    ]
