# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('currency', models.CharField(choices=[(b'PHP', b'PHP')], max_length=3)),
            ],
        ),
    ]
